version: "3.7"
services:
  app:
    build:
      args:
        user: humanbloom
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: smsdashboard
    container_name: smsdashboard-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - smsdashboard

  db:
    image: mysql:5.7
    container_name: smsdashboard-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysqldata:/var/lib/mysql3/
    ports:
      - "3306:3306"
    networks:
      - smsdashboard

  nginx:
    image: nginx:1.17-alpine
    container_name: smsdashboard-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - smsdashboard

  redisdb:
    image: redis:alpine
    container_name: smsdashboard-redisdb
    ports:
      - 6389:6379
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redisdata:/data
    networks:
      - smsdashboard

networks:
  smsdashboard:
    driver: bridge

volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local
